POST http://localhost:3333/events
Content-Type: application/json

{
  "title": 123,
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/1062b011-c87e-4539-b0c5-59fe765bc77f/attendees
Content-Type: application/json

{
  "name": "Pedro",
  "email": "pedro@teste.com.br"
}

### 

GET http://localhost:3333/events/1062b011-c87e-4539-b0c5-59fe765bc77f
Content-Type: application/json


### 


GET http://localhost:3333/attendees/3/badge
Content-Type: application/json


### 

GET http://localhost:3333/attendees/4/check-in
Content-Type: application/json


### 

GET http://localhost:3333/events/1062b011-c87e-4539-b0c5-59fe765bc77f/attendees?query=Pedro
Content-Type: application/json
